const kelimealani = [
  {
    "kelime":"Apple",
    "anlamı":"elma",
    "image":"apple.png"
  },{
    "kelime":"Banana",
    "anlamı":"muz",
    "image":"muz.jpg"
  },
  {
    "kelime":"Cheryy",
    "anlamı":"kiraz",
    "image":"kiraz.png"
  },
  {
    "kelime":"lemon",
    "anlamı":"limon",
    "image":"limon.png"
  },
  {
    "kelime":"kiwi",
    "anlamı":"kivi",
    "image":"kivi.jpg"
  },
  {
    "kelime":"Mandarin",
    "anlamı":"Mandalina",
    "image":"mandalina.png"
  },
  {
    "kelime":"Melon",
    "anlamı":"Kavun",
    "image":"kavun.png"
  },
  {
    "kelime":"Pear",
    "anlamı":"Armut",
    "image":"armut.png"
  },
  {
    "kelime":"strawberry ",
    "anlamı":"çilek",
    "image":"cilek.png"
  },
  {
    "kelime":"Watermelon",
    "anlamı":"karpuz",
    "image":"karpuz.png"
  },
  {
    "kelime":"Berry",
    "anlamı":"dut",
    "image":"dut.png"
  },
  {
    "kelime":"Cucumber",
    "anlamı":"Salatalık",
    "image":"salatalık.png"
  },
  {
    "kelime":"Almond",
    "anlamı":"Badem",
    "image":"badem.png"
  },

];